# Generated by Django 5.2.7 on 2025-10-31 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactsFactory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_cont",
                    models.EmailField(help_text="Почта завода", max_length=254),
                ),
                ("country_cont", models.CharField(help_text="Страна", max_length=100)),
                ("city_cont", models.CharField(help_text="Город", max_length=100)),
                ("street_cont", models.CharField(help_text="Улица", max_length=100)),
                (
                    "number_phone_cont",
                    models.CharField(help_text="Номер телефона", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductsFactory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_pr",
                    models.CharField(help_text="Название продукта", max_length=100),
                ),
                (
                    "models_pr",
                    models.CharField(help_text="Название модели", max_length=100),
                ),
                ("release_pr", models.DateField(help_text="Дата выхода продукта")),
            ],
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        help_text="звенья",
                        verbose_name="factory_level",
                    ),
                ),
                (
                    "name_fact",
                    models.CharField(help_text="Название завода", max_length=30),
                ),
                (
                    "debt_fact",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Задолженность с точностью до копеек",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "time_create_fact",
                    models.TimeField(auto_now_add=True, help_text="Время заполнения"),
                ),
                (
                    "contacts_fact",
                    models.ForeignKey(
                        help_text="Контакты завода",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.contactsfactory",
                    ),
                ),
                (
                    "supplier_fact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.network",
                        verbose_name="Поставщик",
                    ),
                ),
                (
                    "products_fact",
                    models.ManyToManyField(
                        help_text="Продукты", to="network.productsfactory"
                    ),
                ),
            ],
            options={
                "ordering": ["debt_fact"],
            },
        ),
    ]
